name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t sigplac-api .
    
    - name: Run container in background
      run: |
        docker run -d --name sigplac-api -p 8000:8000 \
        -e SIGPLAC_API4AI_KEY="dummy_key_for_testing" \
        sigplac-api
        sleep 10  # Espera o servidor iniciar
        
    - name: Test API health
      run: |
        curl -sSf http://localhost:8000/docs > /dev/null
        echo "Health check passed!"
        
    - name: Cleanup
      if: always()
      run: |
        docker stop sigplac-api || true
        docker rm sigplac-api || true
